Quizly-Project/quizly-Nest

- src/app.module.ts
- src/play/play.service.spec.ts
- src/play/play.service.ts
- src/quiz/quiz.service.ts
> feat: playService 추가함

- src/play/play.service.ts
- src/quiz-game/quiz-game.gateway.ts
- src/quiz/quiz.service.ts
- static/index.html
퀴즈 시작 후 타이머가 발동되며, 타임 아웃이 되면 해당 퀴즈 답이 클라이언트로 브로드캐스트 된다.
> feat: 영역인식, 오답 여부 확인, 정답/ 오답 결과 저장(휘발성), 퀴즈 그룹 시작, 다음 퀴즈 기능 추가 

- src/interfaces/room.interface.ts
- src/play/play.service.ts
- src/quiz-game/quiz-game.gateway.ts
- src/quiz/quiz.service.ts
- src/room/room.service.ts
- src/userPosition/userPosition.service.ts
- static/index.html
**** quizs를 quizzes로 변경함
현재 pull 하지 않고 작업한 fix와 main에서 pull 수행 후 작업한 fix_quizzes가 충돌 발생 이를 수정해서 머지하려고 함
> fix: quizs를 quizzes로 변경

- src/interfaces/room.interface.ts
- src/play/play.service.ts
- src/quiz-game/quiz-game.gateway.ts
- src/quiz/quiz.service.ts
- src/room/room.service.ts
- src/userPosition/userPosition.service.ts
- static/index.html
> fix 브랜치에서 fix_quizzes 브랜치로 머지한 것 체크한 후 main 브랜치로 머지를 진행

- package-lock.json
- package.json
- src/app.module.ts
- src/livekit/livekit.controller.ts
- src/livekit/livekit.module.ts
- src/livekit/livekit.service.ts
- src/main.ts
- tsconfig.json
feat: openvidu를 이용한 화상채팅 기능 구현 완료
> feat: openvidu를 이용한 화상채팅 기능 구현 완료

- src/main.ts
openvidu port crash 문제로 main에서 listen port 3000->3001로 변경
> docs: openvidu port crash 문제로 main에서 listen port 3000->3001로 변경

- src/main.ts
- src/quiz-game/quiz-game.gateway.ts
충돌되는 포트번호 정리 및 기존 포트들 관리하기 용이하게 번호 재지정
> doc: 포트번호 정리

- src/quiz-game/quiz-game.gateway.ts
- src/room/room.service.ts
- src/userPosition/userPosition.service.ts
fix
1. 모델 정보와 텍스트 정보가 일치하지 않는 문제 해결 
feat
1. 새 클라이언트에 대한 모델 정보를 모든 클라이언트에게 전송함
> 모델 정보 저장 문제 수정 및 새 클라이언트 모델 정보 브로드 캐스트 

- src/chat/chat.gateway.ts
- src/chat/chat.service.ts
1. chat 관련 서비스 작성
2. chat 관련 게이트웨이 작성(이벤트)
> feat: chat 관련 서비스 및 게이트 웨이 작성

- src/quiz-game/quiz-game.gateway.ts
**작업 내용**
- 특권 포트 사용 중지 및 포트 번호 관리 용이함을 위해  quiz-game.gateway 81->3004번으로 포트 번호 변경.
> docs: quiz-game gateway port 81 -> 3004로 변경

- src/chat/chat.gateway.ts
- src/chat/chat.service.ts
- src/play/play.service.ts
- src/userPosition/userPosition.service.ts
feat:
1. user-left 브로드캐스팅 수행 
2. user-joined 브로드캐스팅 수행
> feat: user-left, user-joined 이벤트 추가함

- src/chat/chat.gateway.ts
- src/chat/chat.service.ts
> fix: 채팅기능 수정

- src/quiz-game/quiz-game.gateway.ts
- src/room/room.service.ts
- src/userPosition/userPosition.service.ts
> feat: 매개변수 타입 지정 및 예외처리 2

- src/interfaces/clientPosition.interface.ts
- src/play/play.service.ts
- src/quiz/quiz.service.ts
- src/room/room.service.ts
- src/userPosition/userPosition.service.ts
1. 초당 30회 위치 값 모든 클라이언트에게 전송하는 로직 수정 및 불필요한 코드 제거 
2. 문제가 작성되는 시간을 고려하여 타이머 1.5초를 더 계산하게 함
> feat: 초당 30회 위치 값 전송 기능 및 타이머 1.5초 추가 

- src/userPosition/userPosition.service.ts
**작업 내용**
- 오답 지역으로부터 떨어지는 클라이언트를 맵 정중앙으로 리스폰 되도록 로직 작성
> 떨어지는 캐릭터 리스폰

- src/room/room.service.ts
> roomCode생성 방식 변경

- src/chat/chat.gateway.ts
- src/interfaces/room.interface.ts
- src/openai/openai.service.ts
- src/play/play.service.ts
- src/quiz-game/quiz-game.gateway.ts
- src/quiz/quiz.service.ts
- src/room/room.service.ts
- src/userPosition/userPosition.service.ts
- static/index.html
1. GPT에 요청해서 정답과 조금 다른 유사 답안을 정답 처리하도록 함
> Connect open ai

- src/play/play.service.ts
- src/quiz-game/quiz-game.gateway.ts
- src/room/room.service.ts
- src/userPosition/userPosition.service.ts
> feat: 퀴즈 시작할 때 위치 초기화

- src/quiz-game/quiz-game.gateway.ts
- src/room/room.service.ts
> feat: nickName 중복체크

- src/play/play.service.ts
- src/room/room.service.ts
> feat: 값이 갱신되지 않던 문제 해결
